- name: Configure sudo on all servers
  hosts: linux
  become: yes

  tasks:
    - name: Add sudoers file for users
      copy:
        dest: /etc/sudoers.d/ansible-users
        content: |
          administrator ALL=(ALL) NOPASSWD:/usr/bin/yum,/usr/bin/dnf,/usr/bin/apt
          wazuh ALL=(ALL) NOPASSWD:/usr/bin/yum,/usr/bin/dnf,/usr/bin/apt
          moodle ALL=(ALL) NOPASSWD:/usr/bin/yum,/usr/bin/dnf,/usr/bin/apt
          coreload ALL=(ALL) NOPASSWD:/usr/bin/yum,/usr/bin/dnf,/usr/bin/apt
        mode: '0440'