- name: Install packages on all Linux servers
  hosts: linux
  become: yes

  tasks:
    - name: Ensure editors are installed
      package:
        name:
          - vim
          - nano
          - neovim
        state: present
